source 'http://rubygems.org'

gem 'rails', '3.0.3'

gem 'sqlite3-ruby', :require => 'sqlite3'
gem 'mysql', ">=2.8.1"
gem 'eco_apps_util', '>= 0.2.0'
gem 'eco_apps', '>= 0.2.0'

group :development, :test do
  gem 'rspec', '>= 2.0.0'
  gem 'rspec-rails', '>= 2.0.0'
  gem 'ruby-debug'
end
